name: Create Secrets Gist

on:
  workflow_call:
    inputs:
      ms_name:
        required: true
        type: string
      build_env:
        required: true
        type: string
      release_version:
        required: false
        type: string
        default: ''
      secrets_obj:
        description: 'JSON string of secrets object'
        required: true
        type: string
      gist_token:
        required: false
        type: string
    outputs:
      gist_id:
        description: 'Created Gist ID'
        value: ${{ jobs.create-gist.outputs.gist_id }}
      gist_url:
        description: 'Created Gist URL'
        value: ${{ jobs.create-gist.outputs.gist_url }}

jobs:
  create-gist:
    runs-on: ubuntu-latest
    outputs:
      gist_id: ${{ steps.create.outputs.gist_id }}
      gist_url: ${{ steps.create.outputs.gist_url }}
    steps:
      - name: Create Gist
        uses: actions/github-script@v6
        id: create
        env:
          CA_CERT: ${{ secrets.GH_CA_CERT }}
        with:
          github-token: ${{ inputs.gist_token || github.token }}
          script: |
            const https = require('https');
            
            const msName = '${{ inputs.ms_name }}';
            const buildEnv = '${{ inputs.build_env }}';
            const releaseVersion = '${{ inputs.release_version }}';
            const secretsObj = JSON.parse('${{ inputs.secrets_obj }}');
            
            // Create metadata
            const metadata = {
              releaseVersion: releaseVersion || '',
              msName: msName,
              buildEnv: buildEnv,
              status: 'awaiting_input',
              created_at: new Date().toISOString(),
              processed_by: '${{ github.actor }}'
            };
            
            const description = releaseVersion 
              ? `Secrets Input for ${msName} (${buildEnv}) - Release ${releaseVersion}`
              : `Secrets Input for ${msName} (${buildEnv})`;
            
            const agent = process.env.CA_CERT?.trim()
              ? new https.Agent({
                  ca: Buffer.from(process.env.CA_CERT.trim(), 'utf8'),
                  rejectUnauthorized: true
                })
              : null;
            
            const gistResponse = await github.rest.gists.create({
              description: description,
              public: false,
              files: {
                'secretsNeedsInput.json': {
                  content: JSON.stringify(secretsObj, null, 2)
                },
                'metadata.json': {
                  content: JSON.stringify(metadata, null, 2)
                }
              },
              request: agent ? { agent } : undefined
            });
            
            console.log(`Created gist: ${gistResponse.data.id}`);
            console.log(`Gist URL: ${gistResponse.data.html_url}`);
            
            core.setOutput('gist_id', gistResponse.data.id);
            core.setOutput('gist_url', gistResponse.data.html_url);

